steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/pawconscious-mesh-2026/acp-images/mesh-api:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/pawconscious-mesh-2026/acp-images/mesh-api:latest'
      - '-f'
      - 'services/mesh_api/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/pawconscious-mesh-2026/acp-images/mesh-api'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mesh-api'
      - '--image=us-central1-docker.pkg.dev/pawconscious-mesh-2026/acp-images/mesh-api:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--quiet'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'mesh-api'
      - '--region=us-central1'
      - '--to-latest'
      - '--quiet'
images:
  - 'us-central1-docker.pkg.dev/pawconscious-mesh-2026/acp-images/mesh-api:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/pawconscious-mesh-2026/acp-images/mesh-api:latest'
options:
  logging: CLOUD_LOGGING_ONLY
