steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/pawconscious-mesh-2026/acp-images/mesh-api:v0.2.1-s2a1'
      - '-f'
      - 'services/mesh_api/Dockerfile'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/pawconscious-mesh-2026/acp-images/mesh-api:v0.2.1-s2a1'
options:
  logging: CLOUD_LOGGING_ONLY
